---
fixtures:
  repositories:
    iptables: https://github.com/simp/pupmod-simp-iptables
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
  symlinks:
    tpm2: "#{source_dir}"
