---
HOSTS:
  el7:
    roles:
    - tpm
    platform: el-7-x86_64
    box: centos/7
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    yum_repos:
      simp_unstable:
        baseurl: https://download.simp-project.com/simp/yum/rolling/6/el/$releasever/$basearch/simp/
        gpgcheck: 0
    family: centos-cloud/centos-7
    gce_machine_type: n1-standard-2
  el8:
    roles:
    - default
    - tpm
    platform: el-8-x86_64
    box: generic/centos8
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    yum_repos:
      simp_unstable:
        baseurl: https://download.simp-project.com/simp/yum/unstable/6/el/$releasever/$basearch/simp/
        gpgcheck: 0
    family: centos-cloud/centos-stream-8
    gce_machine_type: n1-standard-2
CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 512
  synced_folder: enabled
  ssh:
    timeout: 2
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'puppet7') %>"
